services:
  backend:
    build: .
    container_name: backend-app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Edookati@2025
      - DB_NAME=userdb
      - JWT_SECRET=supersecretkey
    ports:
      - "3001:3000"
    depends_on:
      - db
    command: /bin/sh -c "sleep 30 && npm start"
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Edookati@2025
      MYSQL_DATABASE: userdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
